- name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "pandas<2.0.0"
          pip install "numpy<2.0.0"
          # Direct link to the stable version to bypass the 'None Found' error
          pip install https://github.com/twopirllc/pandas-ta/archive/refs/heads/main.zip
          pip install -r requirements.txt
